/* 
 * Proximax P2P Storage REST API
 *
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: proximax.storage@proximax.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Io.Xpx.Client.SwaggerDateConverter;

namespace Io.Xpx.Model
{
    /// <summary>
    /// MultisigInfo
    /// </summary>
    [DataContract]
    public partial class MultisigInfo :  IEquatable<MultisigInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultisigInfo" /> class.
        /// </summary>
        /// <param name="CosignatoriesCount">CosignatoriesCount.</param>
        /// <param name="MinCosignatories">MinCosignatories.</param>
        public MultisigInfo(int? CosignatoriesCount = default(int?), int? MinCosignatories = default(int?))
        {
            this.CosignatoriesCount = CosignatoriesCount;
            this.MinCosignatories = MinCosignatories;
        }
        
        /// <summary>
        /// Gets or Sets CosignatoriesCount
        /// </summary>
        [DataMember(Name="cosignatoriesCount", EmitDefaultValue=false)]
        public int? CosignatoriesCount { get; set; }

        /// <summary>
        /// Gets or Sets MinCosignatories
        /// </summary>
        [DataMember(Name="minCosignatories", EmitDefaultValue=false)]
        public int? MinCosignatories { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MultisigInfo {\n");
            sb.Append("  CosignatoriesCount: ").Append(CosignatoriesCount).Append("\n");
            sb.Append("  MinCosignatories: ").Append(MinCosignatories).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as MultisigInfo);
        }

        /// <summary>
        /// Returns true if MultisigInfo instances are equal
        /// </summary>
        /// <param name="other">Instance of MultisigInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MultisigInfo other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.CosignatoriesCount == other.CosignatoriesCount ||
                    this.CosignatoriesCount != null &&
                    this.CosignatoriesCount.Equals(other.CosignatoriesCount)
                ) && 
                (
                    this.MinCosignatories == other.MinCosignatories ||
                    this.MinCosignatories != null &&
                    this.MinCosignatories.Equals(other.MinCosignatories)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.CosignatoriesCount != null)
                    hash = hash * 59 + this.CosignatoriesCount.GetHashCode();
                if (this.MinCosignatories != null)
                    hash = hash * 59 + this.MinCosignatories.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
