/* 
 * Proximax P2P Storage REST API
 *
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: proximax.storage@proximax.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Io.Xpx.Client;
using Io.Xpx.Api;

namespace Io.Xpx.Test
{
    /// <summary>
    ///  Class for testing DirectoryLoadApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DirectoryLoadApiTests
    {
        private DirectoryLoadApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DirectoryLoadApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DirectoryLoadApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DirectoryLoadApi
            //Assert.IsInstanceOfType(typeof(DirectoryLoadApi), instance, "instance is a DirectoryLoadApi");
        }

        
        /// <summary>
        /// Test LoadDirectoryUsingGET
        /// </summary>
        [Test]
        public void LoadDirectoryUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nemHash = null;
            //var response = instance.LoadDirectoryUsingGET(nemHash);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
    }

}
