/* 
 * Proximax P2P Storage REST API
 *
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: alvin.reyes@botmill.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Io.Xpx.Client;
using Io.Xpx.Api;
using Io.Xpx.Model;

namespace Io.Xpx.Test
{
    /// <summary>
    ///  Class for testing NodeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class NodeApiTests
    {
        private NodeApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NodeApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NodeApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' NodeApi
            //Assert.IsInstanceOfType(typeof(NodeApi), instance, "instance is a NodeApi");
        }

        
        /// <summary>
        /// Test CheckNodeUsingGET
        /// </summary>
        [Test]
        public void CheckNodeUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.CheckNodeUsingGET();
            //Assert.IsInstanceOf<GenericResponseMessage> (response, "response is GenericResponseMessage");
        }
        
        /// <summary>
        /// Test GetNodeInfoUsingGET
        /// </summary>
        [Test]
        public void GetNodeInfoUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetNodeInfoUsingGET();
            //Assert.IsInstanceOf<NodeInfo> (response, "response is NodeInfo");
        }
        
        /// <summary>
        /// Test SetBlockchainNodeConnectionUsingPOST
        /// </summary>
        [Test]
        public void SetBlockchainNodeConnectionUsingPOSTTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string network = null;
            //string domain = null;
            //string port = null;
            //var response = instance.SetBlockchainNodeConnectionUsingPOST(network, domain, port);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
    }

}
