/* 
 * Proximax P2P Storage REST API
 *
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: alvin.reyes@botmill.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Io.Xpx.Api;
using Io.Xpx.Model;
using Io.Xpx.Client;
using System.Reflection;

namespace Io.Xpx.Test
{
    /// <summary>
    ///  Class for testing AccountInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountInfoTests
    {
        // TODO uncomment below to declare an instance variable for AccountInfo
        //private AccountInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountInfo
            //instance = new AccountInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountInfo
        /// </summary>
        [Test]
        public void AccountInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountInfo
            //Assert.IsInstanceOfType<AccountInfo> (instance, "variable 'instance' is a AccountInfo");
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Test]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'Importance'
        /// </summary>
        [Test]
        public void ImportanceTest()
        {
            // TODO unit test for the property 'Importance'
        }
        /// <summary>
        /// Test the property 'KeyPair'
        /// </summary>
        [Test]
        public void KeyPairTest()
        {
            // TODO unit test for the property 'KeyPair'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'MultisigInfo'
        /// </summary>
        [Test]
        public void MultisigInfoTest()
        {
            // TODO unit test for the property 'MultisigInfo'
        }
        /// <summary>
        /// Test the property 'NumHarvestedBlocks'
        /// </summary>
        [Test]
        public void NumHarvestedBlocksTest()
        {
            // TODO unit test for the property 'NumHarvestedBlocks'
        }
        /// <summary>
        /// Test the property 'VestedBalance'
        /// </summary>
        [Test]
        public void VestedBalanceTest()
        {
            // TODO unit test for the property 'VestedBalance'
        }

    }

}
