/* 
 * Proximax P2P Storage REST API
 *
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: alvin.reyes@botmill.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Io.Xpx.Api;
using Io.Xpx.Model;
using Io.Xpx.Client;
using System.Reflection;

namespace Io.Xpx.Test
{
    /// <summary>
    ///  Class for testing AccountMetaDataPair
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountMetaDataPairTests
    {
        // TODO uncomment below to declare an instance variable for AccountMetaDataPair
        //private AccountMetaDataPair instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountMetaDataPair
            //instance = new AccountMetaDataPair();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountMetaDataPair
        /// </summary>
        [Test]
        public void AccountMetaDataPairInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountMetaDataPair
            //Assert.IsInstanceOfType<AccountMetaDataPair> (instance, "variable 'instance' is a AccountMetaDataPair");
        }

        /// <summary>
        /// Test the property 'Entity'
        /// </summary>
        [Test]
        public void EntityTest()
        {
            // TODO unit test for the property 'Entity'
        }
        /// <summary>
        /// Test the property 'MetaData'
        /// </summary>
        [Test]
        public void MetaDataTest()
        {
            // TODO unit test for the property 'MetaData'
        }

    }

}
