/* 
 * Proximax P2P Storage REST API
 *
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: alvin.reyes@botmill.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Io.Xpx.Api;
using Io.Xpx.Model;
using Io.Xpx.Client;
using System.Reflection;

namespace Io.Xpx.Test
{
    /// <summary>
    ///  Class for testing Amount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AmountTests
    {
        // TODO uncomment below to declare an instance variable for Amount
        //private Amount instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Amount
            //instance = new Amount();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Amount
        /// </summary>
        [Test]
        public void AmountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Amount
            //Assert.IsInstanceOfType<Amount> (instance, "variable 'instance' is a Amount");
        }

        /// <summary>
        /// Test the property 'NumMicroNem'
        /// </summary>
        [Test]
        public void NumMicroNemTest()
        {
            // TODO unit test for the property 'NumMicroNem'
        }
        /// <summary>
        /// Test the property 'NumNem'
        /// </summary>
        [Test]
        public void NumNemTest()
        {
            // TODO unit test for the property 'NumNem'
        }

    }

}
