/* 
 * Proximax P2P Storage REST API
 *
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: alvin.reyes@botmill.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Io.Xpx.Api;
using Io.Xpx.Model;
using Io.Xpx.Client;
using System.Reflection;

namespace Io.Xpx.Test
{
    /// <summary>
    ///  Class for testing BlockAmount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BlockAmountTests
    {
        // TODO uncomment below to declare an instance variable for BlockAmount
        //private BlockAmount instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BlockAmount
            //instance = new BlockAmount();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BlockAmount
        /// </summary>
        [Test]
        public void BlockAmountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BlockAmount
            //Assert.IsInstanceOfType<BlockAmount> (instance, "variable 'instance' is a BlockAmount");
        }

        /// <summary>
        /// Test the property 'Raw'
        /// </summary>
        [Test]
        public void RawTest()
        {
            // TODO unit test for the property 'Raw'
        }

    }

}
