/* 
 * Proximax P2P Storage REST API
 *
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: alvin.reyes@botmill.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Io.Xpx.Api;
using Io.Xpx.Model;
using Io.Xpx.Client;
using System.Reflection;

namespace Io.Xpx.Test
{
    /// <summary>
    ///  Class for testing KeyPair
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KeyPairTests
    {
        // TODO uncomment below to declare an instance variable for KeyPair
        //private KeyPair instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KeyPair
            //instance = new KeyPair();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KeyPair
        /// </summary>
        [Test]
        public void KeyPairInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KeyPair
            //Assert.IsInstanceOfType<KeyPair> (instance, "variable 'instance' is a KeyPair");
        }

        /// <summary>
        /// Test the property 'PrivateKey'
        /// </summary>
        [Test]
        public void PrivateKeyTest()
        {
            // TODO unit test for the property 'PrivateKey'
        }
        /// <summary>
        /// Test the property 'PublicKey'
        /// </summary>
        [Test]
        public void PublicKeyTest()
        {
            // TODO unit test for the property 'PublicKey'
        }

    }

}
