/* 
 * Proximax P2P Storage REST API
 *
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: alvin.reyes@botmill.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Io.Xpx.Api;
using Io.Xpx.Model;
using Io.Xpx.Client;
using System.Reflection;

namespace Io.Xpx.Test
{
    /// <summary>
    ///  Class for testing MultisigInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MultisigInfoTests
    {
        // TODO uncomment below to declare an instance variable for MultisigInfo
        //private MultisigInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MultisigInfo
            //instance = new MultisigInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MultisigInfo
        /// </summary>
        [Test]
        public void MultisigInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MultisigInfo
            //Assert.IsInstanceOfType<MultisigInfo> (instance, "variable 'instance' is a MultisigInfo");
        }

        /// <summary>
        /// Test the property 'CosignatoriesCount'
        /// </summary>
        [Test]
        public void CosignatoriesCountTest()
        {
            // TODO unit test for the property 'CosignatoriesCount'
        }
        /// <summary>
        /// Test the property 'MinCosignatories'
        /// </summary>
        [Test]
        public void MinCosignatoriesTest()
        {
            // TODO unit test for the property 'MinCosignatories'
        }

    }

}
