/* 
 * Proximax P2P Storage REST API
 *
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: alvin.reyes@botmill.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Io.Xpx.Api;
using Io.Xpx.Model;
using Io.Xpx.Client;
using System.Reflection;

namespace Io.Xpx.Test
{
    /// <summary>
    ///  Class for testing RequestAnnounceDataSignature
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RequestAnnounceDataSignatureTests
    {
        // TODO uncomment below to declare an instance variable for RequestAnnounceDataSignature
        //private RequestAnnounceDataSignature instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RequestAnnounceDataSignature
            //instance = new RequestAnnounceDataSignature();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RequestAnnounceDataSignature
        /// </summary>
        [Test]
        public void RequestAnnounceDataSignatureInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RequestAnnounceDataSignature
            //Assert.IsInstanceOfType<RequestAnnounceDataSignature> (instance, "variable 'instance' is a RequestAnnounceDataSignature");
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Test]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }

    }

}
