/* 
 * Proximax P2P Storage REST API
 *
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: alvin.reyes@botmill.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Io.Xpx.Api;
using Io.Xpx.Model;
using Io.Xpx.Client;
using System.Reflection;

namespace Io.Xpx.Test
{
    /// <summary>
    ///  Class for testing URI
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class URITests
    {
        // TODO uncomment below to declare an instance variable for URI
        //private URI instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of URI
            //instance = new URI();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of URI
        /// </summary>
        [Test]
        public void URIInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" URI
            //Assert.IsInstanceOfType<URI> (instance, "variable 'instance' is a URI");
        }

        /// <summary>
        /// Test the property 'Absolute'
        /// </summary>
        [Test]
        public void AbsoluteTest()
        {
            // TODO unit test for the property 'Absolute'
        }
        /// <summary>
        /// Test the property 'Authority'
        /// </summary>
        [Test]
        public void AuthorityTest()
        {
            // TODO unit test for the property 'Authority'
        }
        /// <summary>
        /// Test the property 'Fragment'
        /// </summary>
        [Test]
        public void FragmentTest()
        {
            // TODO unit test for the property 'Fragment'
        }
        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Test]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }
        /// <summary>
        /// Test the property 'Opaque'
        /// </summary>
        [Test]
        public void OpaqueTest()
        {
            // TODO unit test for the property 'Opaque'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Test]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Test]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }
        /// <summary>
        /// Test the property 'RawAuthority'
        /// </summary>
        [Test]
        public void RawAuthorityTest()
        {
            // TODO unit test for the property 'RawAuthority'
        }
        /// <summary>
        /// Test the property 'RawFragment'
        /// </summary>
        [Test]
        public void RawFragmentTest()
        {
            // TODO unit test for the property 'RawFragment'
        }
        /// <summary>
        /// Test the property 'RawPath'
        /// </summary>
        [Test]
        public void RawPathTest()
        {
            // TODO unit test for the property 'RawPath'
        }
        /// <summary>
        /// Test the property 'RawQuery'
        /// </summary>
        [Test]
        public void RawQueryTest()
        {
            // TODO unit test for the property 'RawQuery'
        }
        /// <summary>
        /// Test the property 'RawSchemeSpecificPart'
        /// </summary>
        [Test]
        public void RawSchemeSpecificPartTest()
        {
            // TODO unit test for the property 'RawSchemeSpecificPart'
        }
        /// <summary>
        /// Test the property 'RawUserInfo'
        /// </summary>
        [Test]
        public void RawUserInfoTest()
        {
            // TODO unit test for the property 'RawUserInfo'
        }
        /// <summary>
        /// Test the property 'Scheme'
        /// </summary>
        [Test]
        public void SchemeTest()
        {
            // TODO unit test for the property 'Scheme'
        }
        /// <summary>
        /// Test the property 'SchemeSpecificPart'
        /// </summary>
        [Test]
        public void SchemeSpecificPartTest()
        {
            // TODO unit test for the property 'SchemeSpecificPart'
        }
        /// <summary>
        /// Test the property 'UserInfo'
        /// </summary>
        [Test]
        public void UserInfoTest()
        {
            // TODO unit test for the property 'UserInfo'
        }

    }

}
