/* 
 * Proximax P2P Storage REST API
 *
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: proximax.storage@proximax.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Io.Xpx.Client;

namespace Io.Xpx.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPublishAndSubscribeApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </summary>
        /// <remarks>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </remarks>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>Object</returns>
        Object PublishTopicUsingGET (string topic, string message = null);

        /// <summary>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </summary>
        /// <remarks>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </remarks>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> PublishTopicUsingGETWithHttpInfo (string topic, string message = null);
        /// <summary>
        /// Send a message to a published topic
        /// </summary>
        /// <remarks>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </remarks>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>Object</returns>
        Object SendToTopicUsingGET (string topic, string message = null);

        /// <summary>
        /// Send a message to a published topic
        /// </summary>
        /// <remarks>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </remarks>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> SendToTopicUsingGETWithHttpInfo (string topic, string message = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </summary>
        /// <remarks>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </remarks>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> PublishTopicUsingGETAsync (string topic, string message = null);

        /// <summary>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </summary>
        /// <remarks>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </remarks>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PublishTopicUsingGETAsyncWithHttpInfo (string topic, string message = null);
        /// <summary>
        /// Send a message to a published topic
        /// </summary>
        /// <remarks>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </remarks>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> SendToTopicUsingGETAsync (string topic, string message = null);

        /// <summary>
        /// Send a message to a published topic
        /// </summary>
        /// <remarks>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </remarks>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> SendToTopicUsingGETAsyncWithHttpInfo (string topic, string message = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PublishAndSubscribeApi : IPublishAndSubscribeApi
    {
        private Io.Xpx.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PublishAndSubscribeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PublishAndSubscribeApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = Io.Xpx.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PublishAndSubscribeApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PublishAndSubscribeApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Io.Xpx.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Io.Xpx.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled. Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </summary>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>Object</returns>
        public Object PublishTopicUsingGET (string topic, string message = null)
        {
             ApiResponse<Object> localVarResponse = PublishTopicUsingGETWithHttpInfo(topic, message);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled. Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </summary>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > PublishTopicUsingGETWithHttpInfo (string topic, string message = null)
        {
            // verify the required parameter 'topic' is set
            if (topic == null)
                throw new ApiException(400, "Missing required parameter 'topic' when calling PublishAndSubscribeApi->PublishTopicUsingGET");

            var localVarPath = "/pubsub/init/{topic}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (topic != null) localVarPathParams.Add("topic", Configuration.ApiClient.ParameterToString(topic)); // path parameter
            if (message != null) localVarQueryParams.Add("message", Configuration.ApiClient.ParameterToString(message)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PublishTopicUsingGET", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled. Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </summary>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> PublishTopicUsingGETAsync (string topic, string message = null)
        {
             ApiResponse<Object> localVarResponse = await PublishTopicUsingGETAsyncWithHttpInfo(topic, message);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled. Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </summary>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> PublishTopicUsingGETAsyncWithHttpInfo (string topic, string message = null)
        {
            // verify the required parameter 'topic' is set
            if (topic == null)
                throw new ApiException(400, "Missing required parameter 'topic' when calling PublishAndSubscribeApi->PublishTopicUsingGET");

            var localVarPath = "/pubsub/init/{topic}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (topic != null) localVarPathParams.Add("topic", Configuration.ApiClient.ParameterToString(topic)); // path parameter
            if (message != null) localVarQueryParams.Add("message", Configuration.ApiClient.ParameterToString(message)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PublishTopicUsingGET", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Send a message to a published topic Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </summary>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>Object</returns>
        public Object SendToTopicUsingGET (string topic, string message = null)
        {
             ApiResponse<Object> localVarResponse = SendToTopicUsingGETWithHttpInfo(topic, message);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Send a message to a published topic Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </summary>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > SendToTopicUsingGETWithHttpInfo (string topic, string message = null)
        {
            // verify the required parameter 'topic' is set
            if (topic == null)
                throw new ApiException(400, "Missing required parameter 'topic' when calling PublishAndSubscribeApi->SendToTopicUsingGET");

            var localVarPath = "/pubsub/send/to/{topic}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (topic != null) localVarPathParams.Add("topic", Configuration.ApiClient.ParameterToString(topic)); // path parameter
            if (message != null) localVarQueryParams.Add("message", Configuration.ApiClient.ParameterToString(message)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SendToTopicUsingGET", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Send a message to a published topic Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </summary>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> SendToTopicUsingGETAsync (string topic, string message = null)
        {
             ApiResponse<Object> localVarResponse = await SendToTopicUsingGETAsyncWithHttpInfo(topic, message);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Send a message to a published topic Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
        /// </summary>
        /// <exception cref="Io.Xpx.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="topic">Topic</param>
        /// <param name="message">Initial Message (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> SendToTopicUsingGETAsyncWithHttpInfo (string topic, string message = null)
        {
            // verify the required parameter 'topic' is set
            if (topic == null)
                throw new ApiException(400, "Missing required parameter 'topic' when calling PublishAndSubscribeApi->SendToTopicUsingGET");

            var localVarPath = "/pubsub/send/to/{topic}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (topic != null) localVarPathParams.Add("topic", Configuration.ApiClient.ParameterToString(topic)); // path parameter
            if (message != null) localVarQueryParams.Add("message", Configuration.ApiClient.ParameterToString(message)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SendToTopicUsingGET", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

    }
}
